name: Build CustomItems

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Compilar plugin
        run:   gradle build

      - name: Guardar JAR
        uses: actions/upload-artifact@v4
        with:
          name: CustomItems
          path: build/libs/*.jar
